name: Build Docker Image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v3
      - name: Build the image
        run: docker build . --tag wolletd/wg-setup:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the image
        run: docker push wolletd/wg-setup:latest
